CREATE DATABASE CompravenditaAzioni;
USE CompravenditaAzioni;

CREATE TABLE Utenti(
	ID INT NOT NULL AUTO_INCREMENT,
	Nome VARCHAR(50) NOT NULL,
	Cognome VARCHAR(50) NOT NULL,
	DataDiNascita DATE NOT NULL,
	Email VARCHAR(320) NOT NULL UNIQUE,
	`Password` VARCHAR(255) NOT NULL,
	Conto DECIMAL(12, 4) DEFAULT 0,
	PRIMARY KEY (ID)
);

CREATE TABLE Borse(
	MIC VARCHAR(10) NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	PRIMARY KEY (MIC)
);

CREATE TABLE Risorse(
	ID INT NOT NULL AUTO_INCREMENT,
	Symbol VARCHAR(10) NOT NULL,
	Nome VARCHAR(80) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Quotazioni(
	MIC_Borsa VARCHAR(10) NOT NULL,
	ID_Risorsa INT NOT NULL,
	PRIMARY KEY (MIC_Borsa, ID_Risorsa),
	FOREIGN KEY (MIC_Borsa) REFERENCES Borse(MIC),
	FOREIGN KEY (ID_Risorsa) REFERENCES Risorse(ID)
);

CREATE TABLE Azioni(
	ID INT NOT NULL AUTO_INCREMENT,
	DataOraAcquisto TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	Quantità DECIMAL(12,4) NOT NULL,
	DataOraFine TIMESTAMP NULL DEFAULT NULL, # devo forzare null come valore
	ID_Utente INT NOT NULL,
	ID_Risorsa INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_Utente) REFERENCES Utenti(ID) ON DELETE CASCADE,
	FOREIGN KEY (ID_Risorsa) REFERENCES Risorse(ID),
	CHECK(Quantità > 0 AND (DataOraFine IS NULL OR DataOraFine > DataOraAcquisto))
);

DELIMITER //
CREATE TRIGGER `azioni_after_update` 
AFTER UPDATE ON `azioni` 
FOR EACH ROW 
BEGIN
    IF NEW.Quantità = 0 THEN
        UPDATE `azioni` 
        SET DataOraFine = CURRENT_TIMESTAMP()
        WHERE ID = NEW.ID;
    END IF;
END//
DELIMITER ;
